# .scalafmt.conf
version = 3.10.7 
runner.dialect = scala3

# Maximum width of a line
maxColumn = 120

# Alignment options
align.preset = some 
align.openParenCallSite = false
align.openParenDefnSite = false
align.stripMargin = true

# Indentation
indent.main = 4

# Project settings
project.git = true
