# .scalafmt.conf
version = 3.10.7 
runner.dialect = scala3

# Maximum width of a line
maxColumn = 120

# Alignment options
align.preset = some 
align.openParenCallSite = false
align.openParenDefnSite = false
align.stripMargin = true

# Indentation
indent.main = 4

# Spaces
spaces.inImportCurlyBraces = true

# Rewrite Rules (Optional, but recommended)
rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  PreferCurlyFors
]

# Project settings
project.git = true
